spring:
  datasource:
    url: jdbc:mysql://124.222.161.37:3306/doex?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    #    url: jdbc:mysql://localhost:3306/site?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Shookmaker.1147
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shookmaker.exercise.dao

server:
  port: 8090
  servlet:
    context-path: /
springdoc:
  api-docs:
    enabled: true